CREATE DATABASE IF NOT EXISTS manim_ai
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE manim_ai;

-- 用户表:账号密码
DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '用户id',
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '登录账号,唯一不可重复',
    password VARCHAR(100) NOT NULL COMMENT '登录密码',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '系统登录用户表';

-- 动画任务表(保留本地视频,删除try_count,generated_code)
DROP TABLE IF EXISTS task;
CREATE TABLE task (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '任务主键ID',
    user_id INT NOT NULL COMMENT '所属用户id,关联user表id',
    user_input VARCHAR(600) NOT NULL COMMENT '用户输入动画需求',
    video_path VARCHAR(1000) NULL COMMENT '本地视频文件绝对路径',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0处理中 1成功 2失败',
    error_log TEXT NULL COMMENT '失败错误日志',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '动画生成任务表';